// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaNomina.Web.Data;

#nullable disable

namespace SistemaNomina.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303064112_ArregloPropiedadesNullable")]
    partial class ArregloPropiedadesNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaNomina.Web.Models.Department", b =>
                {
                    b.Property<string>("dept_no")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("dept_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("dept_no");

                    b.HasIndex("dept_name")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            dept_no = "IT",
                            dept_name = "Tecnología"
                        },
                        new
                        {
                            dept_no = "HR",
                            dept_name = "Recursos Humanos"
                        },
                        new
                        {
                            dept_no = "FIN",
                            dept_name = "Finanzas"
                        },
                        new
                        {
                            dept_no = "MKT",
                            dept_name = "Marketing"
                        });
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.DeptEmp", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("dept_no")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("from_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("to_date")
                        .HasColumnType("datetime2");

                    b.HasKey("emp_no", "dept_no", "from_date");

                    b.HasIndex("dept_no");

                    b.ToTable("DeptEmps");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.DeptManager", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("dept_no")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("from_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("to_date")
                        .HasColumnType("datetime2");

                    b.HasKey("emp_no", "dept_no", "from_date");

                    b.HasIndex("dept_no");

                    b.ToTable("DeptManagers");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.Employee", b =>
                {
                    b.Property<int>("emp_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("emp_no"));

                    b.Property<DateTime>("birth_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ci")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("hire_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("emp_no");

                    b.HasIndex("ci")
                        .IsUnique();

                    b.HasIndex("correo")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.LogAuditoriaSalario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("DetalleCambio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("LogAuditoriaSalarios");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.Salary", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("from_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("to_date")
                        .HasColumnType("datetime2");

                    b.HasKey("emp_no", "from_date");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.Title", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("from_date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("to_date")
                        .HasColumnType("datetime2");

                    b.HasKey("emp_no", "title", "from_date");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.User", b =>
                {
                    b.Property<int>("emp_no")
                        .HasColumnType("int");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("emp_no");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.DeptEmp", b =>
                {
                    b.HasOne("SistemaNomina.Web.Models.Department", "Department")
                        .WithMany("DeptEmps")
                        .HasForeignKey("dept_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaNomina.Web.Models.Employee", "Employee")
                        .WithMany("DeptEmps")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.DeptManager", b =>
                {
                    b.HasOne("SistemaNomina.Web.Models.Department", "Department")
                        .WithMany("DeptManagers")
                        .HasForeignKey("dept_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaNomina.Web.Models.Employee", "Employee")
                        .WithMany("DeptManagers")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.Salary", b =>
                {
                    b.HasOne("SistemaNomina.Web.Models.Employee", "Employee")
                        .WithMany("Salaries")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.Title", b =>
                {
                    b.HasOne("SistemaNomina.Web.Models.Employee", "Employee")
                        .WithMany("Titles")
                        .HasForeignKey("emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.User", b =>
                {
                    b.HasOne("SistemaNomina.Web.Models.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("SistemaNomina.Web.Models.User", "emp_no")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.Department", b =>
                {
                    b.Navigation("DeptEmps");

                    b.Navigation("DeptManagers");
                });

            modelBuilder.Entity("SistemaNomina.Web.Models.Employee", b =>
                {
                    b.Navigation("DeptEmps");

                    b.Navigation("DeptManagers");

                    b.Navigation("Salaries");

                    b.Navigation("Titles");

                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
